/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-20 01:00:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/board/../common/topbar.jsp", Long.valueOf(1626737480999L));
    _jspx_dependants.put("/views/board/../common/stylesheet.jsp", Long.valueOf(1626737481840L));
    _jspx_dependants.put("/views/board/../common/script.jsp", Long.valueOf(1626737484188L));
    _jspx_dependants.put("/views/board/../common/sidebar.jsp", Long.valueOf(1626738257702L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>게시판</title>\n");
      out.write("<!--Focus Admin: Creative Admin Dashboard  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("    <!-- Standard -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://placehold.it/64.png/000/fff\">\n");
      out.write("    <!-- Retina iPad Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"http://placehold.it/144.png/000/fff\">\n");
      out.write("    <!-- Retina iPhone Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"http://placehold.it/114.png/000/fff\">\n");
      out.write("    <!-- Standard iPad Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://placehold.it/72.png/000/fff\">\n");
      out.write("    <!-- Standard iPhone Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://placehold.it/57.png/000/fff\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- Styles -->\n");
      out.write("    <!-- index -->\n");
      out.write("    <link href=\"/semi/resources/css/lib/calendar2/pignose.calendar.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/chartist/chartist.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/themify-icons.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/owl.carousel.min.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"/semi/resources/css/lib/owl.theme.default.min.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"/semi/resources/css/lib/weather-icons.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("	<!-- boardAdmin -->\n");
      out.write("	<link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/jsgrid/jsgrid-theme.min.css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"/semi/resources/css/lib/jsgrid/jsgrid.min.css\" type=\"text/css\" rel=\"stylesheet\" />\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("	<!-- boardMain\n");
      out.write("    <link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\"> -->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	//Member loginMember = (Member)session.getAttribute("loginMember");

      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div\n");
      out.write("		class=\"sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures\">\n");
      out.write("		<div class=\"nano\">\n");
      out.write("			<div class=\"nano-content\">\n");
      out.write("				<ul>\n");
      out.write("					<div class=\"logo\">\n");
      out.write("						<a href=\"index1.html\"> <!-- <img src=\"assets/images/logo.png\" alt=\"\" /> -->\n");
      out.write("							<span>CovLab</span></a>\n");
      out.write("					</div>\n");
      out.write("					<li class=\"label\">Menu</li>\n");
      out.write("					<ul>\n");
      out.write("						<li><a href=\"/semi/index.jsp\">백신 예약</a></li>\n");
      out.write("						<li><a href=\"/semi/views/information/information.jsp\">뉴스/백신 정보</a></li>\n");
      out.write("						<li>\n");
      out.write("						");
 if(true){ //관리자용
      out.write("\n");
      out.write("							<a href=\"/semi/views/board/boardAdmin.jsp\">접종 후기 관리</a>\n");
      out.write("						");
 }else{ 
      out.write("\n");
      out.write("							<a href=\"/semi/views/board/boardMain.jsp\">접종 후기</a>\n");
      out.write("						");
 } 
      out.write("\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("						");
 if(true){ //로그인
      out.write(" <!--회원가입 창 만들었는데 아니다 싶으면 지워주세여  -->\n");
      out.write("						<a href=\"/semi/views/member/idcheck.jsp\">회원가입</a>\n");
      out.write("							\n");
      out.write("						");
 }else{  //로그인 아닐시 
      out.write("\n");
      out.write("							<a href=\"/semi/index.jsp\">MY PAGE</a>\n");
      out.write("						");
 } 
      out.write("\n");
      out.write("						</li>\n");
      out.write("					</ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("					<li><a class=\"sidebar-sub-toggle\"><i class=\"ti-target\"></i>\n");
      out.write("							Pages <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"page-login.html\">Login</a></li>\n");
      out.write("							<li><a href=\"page-register.html\">Register</a></li>\n");
      out.write("							<li><a href=\"page-reset-password.html\">Forgot password</a></li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li><a href=\"../documentation/index.html\"><i\n");
      out.write("							class=\"ti-file\"></i> Documentation</a></li>\n");
      out.write("					<li><a><i class=\"ti-close\"></i> Logout</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- /# sidebar -->\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"header\">\n");
      out.write(" \n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"float-left\">\n");
      out.write("                        <div class=\"hamburger sidebar-toggle\">\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"float-right\">\n");
      out.write("                        <div class=\"dropdown dib\">\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"ti-bell\"></i>\n");
      out.write("                                \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"dropdown dib\">\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"ti-email\"></i>\n");
      out.write("                                <div class=\"drop-down dropdown-menu dropdown-menu-right\">\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\n");
      out.write("                                        <span class=\"text-left\">2 New Messages</span>\n");
      out.write("                                        <a href=\"email.html\">\n");
      out.write("                                            <i class=\"ti-pencil-alt pull-right\"></i>\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"dropdown-content-body\">\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li class=\"notification-unread\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/1.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li class=\"notification-unread\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/3.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li class=\"text-center\">\n");
      out.write("                                                <a href=\"#\" class=\"more-link\">See All</a>\n");
      out.write("                                            </li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"dropdown dib\">\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\n");
      out.write("                                <span class=\"user-avatar\">John\n");
      out.write("                                    <i class=\"ti-angle-down f-s-10\"></i>\n");
      out.write("                                </span>\n");
      out.write("                                <div class=\"drop-down dropdown-profile dropdown-menu dropdown-menu-right\">\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\n");
      out.write("                                        <span class=\"text-left\">Upgrade Now</span>\n");
      out.write("                                        <p class=\"trial-day\">30 Days Trail</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"dropdown-content-body\">\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-user\"></i>\n");
      out.write("                                                    <span>Profile</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                            \n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-settings\"></i>\n");
      out.write("                                                    <span>Setting</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-lock\"></i>\n");
      out.write("                                                    <span>Lock Screen</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-power-off\"></i>\n");
      out.write("                                                    <span>Logout</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"content-wrap\">\n");
      out.write("		<div class=\"main\">\n");
      out.write("			<div class=\"container-fluid\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-lg-8 p-r-0 title-margin-right\">\n");
      out.write("						<div class=\"page-header\">\n");
      out.write("							<div class=\"page-title\">\n");
      out.write("								<h1>\n");
      out.write("									접종후기 <span> 관리자용</span>\n");
      out.write("								</h1>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- /# column -->\n");
      out.write("					<div class=\"col-lg-4 p-l-0 title-margin-left\">\n");
      out.write("						<div class=\"page-header\">\n");
      out.write("							<div class=\"page-title\">\n");
      out.write("								<ol class=\"breadcrumb\">\n");
      out.write("									<li class=\"breadcrumb-item\"><a href=\"#\">Dashboard</a></li>\n");
      out.write("									<li class=\"breadcrumb-item active\">Table-Jsgrid</li>\n");
      out.write("								</ol>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- /# column -->\n");
      out.write("				</div>\n");
      out.write("				<!-- /# row -->\n");
      out.write("				<div id=\"main-content\">\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-lg-12\">\n");
      out.write("							<div class=\"card\">\n");
      out.write("								<div class=\"jsgrid-table-panel\">\n");
      out.write("									<div id=\"jsGrid\"></div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- /# card -->\n");
      out.write("						</div>\n");
      out.write("						<!-- /# column -->\n");
      out.write("					</div>\n");
      out.write("					<!-- /# row -->\n");
      out.write("\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-lg-12\">\n");
      out.write("							<div class=\"footer\">\n");
      out.write("								<p>\n");
      out.write("									2018 © Admin Board. - <a href=\"#\">example.com</a>\n");
      out.write("								</p>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- index -->\n");
      out.write("\n");
      out.write("    <!-- jquery vendor -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- nano scroller -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\n");
      out.write("   \n");
      out.write("    <!-- sidebar -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/scripts.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- bootstrap -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/calendar-2/moment.latest.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/calendar-2/pignose.calendar.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/calendar-2/pignose.init.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"/semi/resources/js/lib/weather/jquery.simpleWeather.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/weather/weather-init.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/circle-progress/circle-progress.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/circle-progress/circle-progress-init.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/chartist/chartist.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/sparklinechart/jquery.sparkline.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/sparklinechart/sparkline.init.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/owl-carousel/owl.carousel.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/owl-carousel/owl.carousel-init.js\"></script>\n");
      out.write("    <!-- scripit init-->\n");
      out.write("    <script src=\"/semi/resources/js/dashboard2.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- boardAdmin -->\n");
      out.write("	<!-- jquery vendor -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\n");
      out.write("    <!-- nano scroller -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\n");
      out.write("    <!-- sidebar -->\n");
      out.write("    \n");
      out.write("    <!-- bootstrap -->\n");
      out.write("\n");
      out.write("    <!-- JS Grid Scripts Start-->\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/db.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/jsgrid.core.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/jsgrid.load-indicator.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/jsgrid.load-strategies.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/jsgrid.sort-strategies.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/jsgrid.field.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/fields/jsgrid.field.text.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/fields/jsgrid.field.number.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/fields/jsgrid.field.select.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/fields/jsgrid.field.checkbox.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/fields/jsgrid.field.control.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jsgrid/jsgrid-init.js\"></script>\n");
      out.write("    <!-- JS Grid Scripts End-->\n");
      out.write("\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/scripts.js\"></script>\n");
      out.write("    <!-- scripit init-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
