/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
<<<<<<< Updated upstream
 * Generated at: 2021-07-20 01:00:10 UTC
=======
 * Generated at: 2021-07-23 04:20:12 UTC
>>>>>>> Stashed changes
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.information;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class information_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
<<<<<<< Updated upstream
    _jspx_dependants.put("/views/information/../common/sidebar.jsp", Long.valueOf(1626738257702L));
    _jspx_dependants.put("/views/information/../common/topbar.jsp", Long.valueOf(1626737480999L));
=======
    _jspx_dependants.put("/views/information/../common/sidebar.jsp", Long.valueOf(1627013780282L));
    _jspx_dependants.put("/views/information/../common/topbar.jsp", Long.valueOf(1627012414277L));
>>>>>>> Stashed changes
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
<<<<<<< Updated upstream
      out.write("    <title>Focus Admin: Tab</title>\n");
=======
      out.write("    <title>Information</title>\n");
      out.write("\n");
>>>>>>> Stashed changes
      out.write("\n");
      out.write("    <!-- ================= Favicon ================== -->\n");
      out.write("    <!-- Standard -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://placehold.it/64.png/000/fff\">\n");
      out.write("    <!-- Retina iPad Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"http://placehold.it/144.png/000/fff\">\n");
      out.write("    <!-- Retina iPhone Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"http://placehold.it/114.png/000/fff\">\n");
      out.write("    <!-- Standard iPad Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://placehold.it/72.png/000/fff\">\n");
      out.write("    <!-- Standard iPhone Touch Icon-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://placehold.it/57.png/000/fff\">\n");
      out.write("\n");
      out.write("    <!-- Styles -->\n");
      out.write("    <link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
<<<<<<< Updated upstream
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	//Member loginMember = (Member)session.getAttribute("loginMember");

      out.write(" \n");
=======
      out.write("\n");
      out.write("\n");
>>>>>>> Stashed changes
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div\n");
      out.write("		class=\"sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures\">\n");
      out.write("		<div class=\"nano\">\n");
      out.write("			<div class=\"nano-content\">\n");
      out.write("				<ul>\n");
      out.write("					<div class=\"logo\">\n");
      out.write("						<a href=\"index1.html\"> <!-- <img src=\"assets/images/logo.png\" alt=\"\" /> -->\n");
      out.write("							<span>CovLab</span></a>\n");
      out.write("					</div>\n");
      out.write("					<li class=\"label\">Menu</li>\n");
      out.write("					<ul>\n");
      out.write("						<li><a href=\"/semi/index.jsp\">백신 예약</a></li>\n");
      out.write("						<li><a href=\"/semi/views/information/information.jsp\">뉴스/백신 정보</a></li>\n");
<<<<<<< Updated upstream
      out.write("						<li>\n");
      out.write("						");
 if(true){ //관리자용
      out.write("\n");
      out.write("							<a href=\"/semi/views/board/boardAdmin.jsp\">접종 후기 관리</a>\n");
      out.write("						");
 }else{ 
      out.write("\n");
      out.write("							<a href=\"/semi/views/board/boardMain.jsp\">접종 후기</a>\n");
      out.write("						");
 } 
      out.write("\n");
      out.write("						</li>\n");
=======
      out.write("						\n");
>>>>>>> Stashed changes
      out.write("						<li>\n");
      out.write("						");
 if(true){ //로그인
      out.write(" <!--회원가입 창 만들었는데 아니다 싶으면 지워주세여  -->\n");
      out.write("						<a href=\"/semi/views/member/idcheck.jsp\">회원가입</a>\n");
      out.write("							\n");
      out.write("						");
 }else{  //로그인 아닐시 
      out.write("\n");
      out.write("							<a href=\"/semi/index.jsp\">MY PAGE</a>\n");
      out.write("						");
 } 
      out.write("\n");
      out.write("						</li>\n");
<<<<<<< Updated upstream
=======
      out.write("						\n");
      out.write("						");
 if(true){ //관리자 
      out.write("\n");
      out.write("							<li><a href=\"/semi/blistadmin\">접종 후기 관리</a></li>\n");
      out.write("						");
 } else { 
      out.write("\n");
      out.write("							<li><a href=\"/semi/blist\">접종 후기</a></li>\n");
      out.write("						");
 } 
      out.write("\n");
      out.write("						\n");
      out.write("						<li><a href=\"/semi/index.jsp\">MY PAGE</a></li>\n");
>>>>>>> Stashed changes
      out.write("					</ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("					<li><a class=\"sidebar-sub-toggle\"><i class=\"ti-target\"></i>\n");
      out.write("							Pages <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"page-login.html\">Login</a></li>\n");
      out.write("							<li><a href=\"page-register.html\">Register</a></li>\n");
      out.write("							<li><a href=\"page-reset-password.html\">Forgot password</a></li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li><a href=\"../documentation/index.html\"><i\n");
      out.write("							class=\"ti-file\"></i> Documentation</a></li>\n");
      out.write("					<li><a><i class=\"ti-close\"></i> Logout</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- /# sidebar -->\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"header\">\n");
      out.write(" \n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"float-left\">\n");
      out.write("                        <div class=\"hamburger sidebar-toggle\">\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"float-right\">\n");
      out.write("                        <div class=\"dropdown dib\">\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"ti-bell\"></i>\n");
      out.write("                                \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"dropdown dib\">\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"ti-email\"></i>\n");
      out.write("                                <div class=\"drop-down dropdown-menu dropdown-menu-right\">\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\n");
      out.write("                                        <span class=\"text-left\">2 New Messages</span>\n");
      out.write("                                        <a href=\"email.html\">\n");
      out.write("                                            <i class=\"ti-pencil-alt pull-right\"></i>\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"dropdown-content-body\">\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li class=\"notification-unread\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/1.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li class=\"notification-unread\">\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/3.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\n");
      out.write("                                                    <div class=\"notification-content\">\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\n");
      out.write("                                                            PM</small>\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\n");
      out.write("                                                            ...</div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li class=\"text-center\">\n");
      out.write("                                                <a href=\"#\" class=\"more-link\">See All</a>\n");
      out.write("                                            </li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"dropdown dib\">\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\n");
      out.write("                                <span class=\"user-avatar\">John\n");
      out.write("                                    <i class=\"ti-angle-down f-s-10\"></i>\n");
      out.write("                                </span>\n");
      out.write("                                <div class=\"drop-down dropdown-profile dropdown-menu dropdown-menu-right\">\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\n");
      out.write("                                        <span class=\"text-left\">Upgrade Now</span>\n");
      out.write("                                        <p class=\"trial-day\">30 Days Trail</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"dropdown-content-body\">\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-user\"></i>\n");
      out.write("                                                    <span>Profile</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                            \n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-settings\"></i>\n");
      out.write("                                                    <span>Setting</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-lock\"></i>\n");
      out.write("                                                    <span>Lock Screen</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                            <li>\n");
      out.write("                                                <a href=\"#\">\n");
      out.write("                                                    <i class=\"ti-power-off\"></i>\n");
      out.write("                                                    <span>Logout</span>\n");
      out.write("                                                </a>\n");
      out.write("                                            </li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
<<<<<<< Updated upstream
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"content-wrap\">\n");
      out.write("        <div class=\"main\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-8 p-r-0 title-margin-right\">\n");
      out.write("                        <div class=\"page-header\">\n");
      out.write("                            <div class=\"page-title\">\n");
      out.write("                                <h1>Hello, <span>Welcome Here</span></h1>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /# column -->\n");
      out.write("                    <div class=\"col-lg-4 p-l-0 title-margin-left\">\n");
      out.write("                        <div class=\"page-header\">\n");
      out.write("                            <div class=\"page-title\">\n");
      out.write("                                <ol class=\"breadcrumb\">\n");
      out.write("                                    <li class=\"breadcrumb-item\"><a href=\"#\">Dashboard</a></li>\n");
      out.write("                                    <li class=\"breadcrumb-item active\">UI-Tab</li>\n");
      out.write("                                </ol>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /# column -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /# row -->\n");
      out.write("                <section id=\"main-content\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title\">Default Tab</h4>\n");
      out.write("											<!-- Nav tabs -->\n");
      out.write("											<ul class=\"nav nav-tabs\" role=\"tablist\">\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-home\"></i></span> <span class=\"hidden-xs-down\">Home</span></a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-user\"></i></span> <span class=\"hidden-xs-down\">Profile</span></a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-email\"></i></span> <span class=\"hidden-xs-down\">Messages</span></a> </li>\n");
      out.write("											</ul>\n");
      out.write("											<!-- Tab panes -->\n");
      out.write("											<div class=\"tab-content tabcontent-border\">\n");
      out.write("												<div class=\"tab-pane active\" id=\"home\" role=\"tabpanel\">\n");
      out.write("													<div class=\"p-20\">\n");
      out.write("														<h5>Best Clean Tab ever</h5>\n");
      out.write("														<h6>you can use it with the small code</h6>\n");
      out.write("														<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a.</p>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div class=\"tab-pane  p-20\" id=\"profile\" role=\"tabpanel\">2</div>\n");
      out.write("												<div class=\"tab-pane p-20\" id=\"messages\" role=\"tabpanel\">3</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body p-b-0\">\n");
      out.write("											<h4 class=\"card-title\">Customtab Tab</h4>\n");
      out.write("										<!-- Nav tabs -->\n");
      out.write("										<ul class=\"nav nav-tabs customtab\" role=\"tablist\">\n");
      out.write("											<li class=\"nav-item\"> <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home2\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-home\"></i></span> <span class=\"hidden-xs-down\">Home</span></a> </li>\n");
      out.write("											<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile2\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-user\"></i></span> <span class=\"hidden-xs-down\">Profile</span></a> </li>\n");
      out.write("											<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages2\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-email\"></i></span> <span class=\"hidden-xs-down\">Messages</span></a> </li>\n");
      out.write("										</ul>\n");
      out.write("										<!-- Tab panes -->\n");
      out.write("										<div class=\"tab-content\">\n");
      out.write("											<div class=\"tab-pane active\" id=\"home2\" role=\"tabpanel\">\n");
      out.write("												<div class=\"p-20\">\n");
      out.write("													<h5>Best Clean Tab ever</h5>\n");
      out.write("													<h6>you can use it with the small code</h6>\n");
      out.write("													<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a.</p>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("											<div class=\"tab-pane  p-20\" id=\"profile2\" role=\"tabpanel\">2</div>\n");
      out.write("											<div class=\"tab-pane p-20\" id=\"messages2\" role=\"tabpanel\">3</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- row -->\n");
      out.write("							<!-- row -->\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title\">Vertical Tab</h4>\n");
      out.write("											<!-- Nav tabs -->\n");
      out.write("											<div class=\"vtabs\">\n");
      out.write("												<ul class=\"nav nav-tabs tabs-vertical\" role=\"tablist\">\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home4\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-home\"></i></span> <span class=\"hidden-xs-down\">Home</span> </a> </li>\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile4\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-user\"></i></span> <span class=\"hidden-xs-down\">Profile</span></a> </li>\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages4\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-email\"></i></span> <span class=\"hidden-xs-down\">Messages</span></a> </li>\n");
      out.write("												</ul>\n");
      out.write("												<!-- Tab panes -->\n");
      out.write("												<div class=\"tab-content\">\n");
      out.write("													<div class=\"tab-pane active\" id=\"home4\" role=\"tabpanel\">\n");
      out.write("														<div class=\"p-20\">\n");
      out.write("															<h5>Best Clean Tab ever</h5>\n");
      out.write("															<h6>you can use it with the small code</h6>\n");
      out.write("															<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a.</p>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("													<div class=\"tab-pane p-20\" id=\"profile4\" role=\"tabpanel\">2</div>\n");
      out.write("													<div class=\"tab-pane p-20\" id=\"messages4\" role=\"tabpanel\">3</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title\">Customtab vertical Tab</h4>\n");
      out.write("											<!-- Nav tabs -->\n");
      out.write("											<div class=\"vtabs customvtab\">\n");
      out.write("												<ul class=\"nav nav-tabs tabs-vertical\" role=\"tablist\">\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home3\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-home\"></i></span> <span class=\"hidden-xs-down\">Home</span> </a> </li>\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile3\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-user\"></i></span> <span class=\"hidden-xs-down\">Profile</span></a> </li>\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages3\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-email\"></i></span> <span class=\"hidden-xs-down\">Messages</span></a> </li>\n");
      out.write("												</ul>\n");
      out.write("												<!-- Tab panes -->\n");
      out.write("												<div class=\"tab-content\">\n");
      out.write("													<div class=\"tab-pane active\" id=\"home3\" role=\"tabpanel\">\n");
      out.write("														<div class=\"p-20\">\n");
      out.write("															<h5>Best Clean Tab ever</h5>\n");
      out.write("															<h6>you can use it with the small code</h6>\n");
      out.write("															<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a.</p>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("													<div class=\"tab-pane  p-20\" id=\"profile3\" role=\"tabpanel\">2</div>\n");
      out.write("													<div class=\"tab-pane p-20\" id=\"messages3\" role=\"tabpanel\">3</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- row -->\n");
      out.write("							<!-- row -->\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title m-b-40\">Tab with dropdown</h4>\n");
      out.write("											<ul class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link active\" id=\"home-tab\" data-toggle=\"tab\" href=\"#home5\" role=\"tab\" aria-controls=\"home5\" aria-expanded=\"true\"><span class=\"hidden-sm-up\"><i class=\"ti-home\"></i></span> <span class=\"hidden-xs-down\">Home</span></a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link\" id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile5\" role=\"tab\" aria-controls=\"profile\"><span class=\"hidden-sm-up\"><i class=\"ti-user\"></i></span> <span class=\"hidden-xs-down\">Profile</span></a></li>\n");
      out.write("												<li class=\"nav-item dropdown\">\n");
      out.write("													<a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("														<span class=\"hidden-sm-up\"><i class=\"ti-email\"></i></span> <span class=\"hidden-xs-down\">Dropdown</span>\n");
      out.write("													</a>\n");
      out.write("													<div class=\"dropdown-menu\"> <a class=\"dropdown-item\" id=\"dropdown1-tab\" href=\"#dropdown1\" role=\"tab\" data-toggle=\"tab\" aria-controls=\"dropdown1\">@fat</a> <a class=\"dropdown-item\" id=\"dropdown2-tab\" href=\"#dropdown2\" role=\"tab\" data-toggle=\"tab\" aria-controls=\"dropdown2\">@mdo</a> </div>\n");
      out.write("												</li>\n");
      out.write("											</ul>\n");
      out.write("											<div class=\"tab-content tabcontent-border p-20\" id=\"myTabContent\">\n");
      out.write("												<div role=\"tabpanel\" class=\"tab-pane fade show active\" id=\"home5\" aria-labelledby=\"home-tab\">\n");
      out.write("													<p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>\n");
      out.write("												</div>\n");
      out.write("												<div class=\"tab-pane fade\" id=\"profile5\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\n");
      out.write("													<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>\n");
      out.write("												</div>\n");
      out.write("												<div class=\"tab-pane fade\" id=\"dropdown1\" role=\"tabpanel\" aria-labelledby=\"dropdown1-tab\">\n");
      out.write("													<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>\n");
      out.write("												</div>\n");
      out.write("												<div class=\"tab-pane fade\" id=\"dropdown2\" role=\"tabpanel\" aria-labelledby=\"dropdown2-tab\">\n");
      out.write("													<p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body p-b-0\">\n");
      out.write("											<h4 class=\"card-title\">Customtab2 Tab</h4>\n");
      out.write("											<!-- Nav tabs -->\n");
      out.write("											<ul class=\"nav nav-tabs customtab2\" role=\"tablist\">\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home7\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-home\"></i></span> <span class=\"hidden-xs-down\">Home</span></a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile7\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-user\"></i></span> <span class=\"hidden-xs-down\">Profile</span></a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages7\" role=\"tab\"><span class=\"hidden-sm-up\"><i class=\"ti-email\"></i></span> <span class=\"hidden-xs-down\">Messages</span></a> </li>\n");
      out.write("											</ul>\n");
      out.write("											<!-- Tab panes -->\n");
      out.write("											<div class=\"tab-content\">\n");
      out.write("												<div class=\"tab-pane active\" id=\"home7\" role=\"tabpanel\">\n");
      out.write("													<div class=\"p-20\">\n");
      out.write("														<h5>Best Clean Tab ever</h5>\n");
      out.write("														<h6>you can use it with the small code</h6>\n");
      out.write("														<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a.</p>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div class=\"tab-pane  p-20\" id=\"profile7\" role=\"tabpanel\">2</div>\n");
      out.write("												<div class=\"tab-pane p-20\" id=\"messages7\" role=\"tabpanel\">3</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- row -->\n");
      out.write("							<div class=\"row\">\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title\">Nav Pills Tabs</h4>\n");
      out.write("											<ul class=\"nav nav-pills m-t-30 m-b-30\">\n");
      out.write("												<li class=\" nav-item\"> <a href=\"#navpills-1\" class=\"nav-link active\" data-toggle=\"tab\" aria-expanded=\"false\">Tab One</a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a href=\"#navpills-2\" class=\"nav-link\" data-toggle=\"tab\" aria-expanded=\"false\">Tab Two</a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a href=\"#navpills-3\" class=\"nav-link\" data-toggle=\"tab\" aria-expanded=\"true\">Tab Three</a> </li>\n");
      out.write("											</ul>\n");
      out.write("											<div class=\"tab-content br-n pn\">\n");
      out.write("												<div id=\"navpills-1\" class=\"tab-pane active\">\n");
      out.write("													<div class=\"row\">\n");
      out.write("														<div class=\"col-md-4\"> <img src=\"assets/images/c1.jpg\" class=\"img-fluid thumbnail m-r-15\"> </div>\n");
      out.write("														<div class=\"col-md-8\"> Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.\n");
      out.write("															<p>\n");
      out.write("																<br/> Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid.</p>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div id=\"navpills-2\" class=\"tab-pane\">\n");
      out.write("													<div class=\"row\">\n");
      out.write("														<div class=\"col-md-8\"> Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.\n");
      out.write("															<p>\n");
      out.write("																<br/> Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid.</p>\n");
      out.write("														</div>\n");
      out.write("														<div class=\"col-md-4\"> <img src=\"assets/images/c1.jpg\" class=\"img-fluid thumbnail mr25\"> </div>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div id=\"navpills-3\" class=\"tab-pane\">\n");
      out.write("													<div class=\"row\">\n");
      out.write("														<div class=\"col-md-4\"> <img src=\"assets/images/c1.jpg\" class=\"img-fluid thumbnail mr25\"> </div>\n");
      out.write("														<div class=\"col-md-8\"> Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.\n");
      out.write("															<p>\n");
      out.write("																<br/> Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid.</p>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title\">Nav Pills Tabs</h4>\n");
      out.write("											<ul class=\"nav nav-pills m-t-30 justify-content-end m-b-30\">\n");
      out.write("												<li class=\" nav-item\"> <a href=\"#navpills2-1\" class=\"nav-link active\" data-toggle=\"tab\" aria-expanded=\"false\">Tab One</a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a href=\"#navpills2-2\" class=\"nav-link\" data-toggle=\"tab\" aria-expanded=\"false\">Tab Two</a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a href=\"#navpills2-3\" class=\"nav-link\" data-toggle=\"tab\" aria-expanded=\"true\">Tab Three</a> </li>\n");
      out.write("											</ul>\n");
      out.write("											<div class=\"tab-content br-n pn\">\n");
      out.write("												<div id=\"navpills2-1\" class=\"tab-pane active\">\n");
      out.write("													<div class=\"row\">\n");
      out.write("														<div class=\"col-md-4\"> <img src=\"assets/images/c1.jpg\" class=\"img-fluid thumbnail m-r-15\"> </div>\n");
      out.write("														<div class=\"col-md-8\"> Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.\n");
      out.write("															<p>\n");
      out.write("																<br/> Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid.</p>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div id=\"navpills2-2\" class=\"tab-pane\">\n");
      out.write("													<div class=\"row\">\n");
      out.write("														<div class=\"col-md-8\"> Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.\n");
      out.write("															<p>\n");
      out.write("																<br/> Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid.</p>\n");
      out.write("														</div>\n");
      out.write("														<div class=\"col-md-4\"> <img src=\"assets/images/c1.jpg\" class=\"img-fluid thumbnail mr25\"> </div>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div id=\"navpills2-3\" class=\"tab-pane\">\n");
      out.write("													<div class=\"row\">\n");
      out.write("														<div class=\"col-md-4\"> <img src=\"assets/images/c1.jpg\" class=\"img-fluid thumbnail mr25\"> </div>\n");
      out.write("														<div class=\"col-md-8\"> Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica.\n");
      out.write("															<p>\n");
      out.write("																<br/> Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid.</p>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title\">Tab with icon</h4>\n");
      out.write("											<!-- Nav tabs -->\n");
      out.write("											<ul class=\"nav nav-tabs\" role=\"tablist\">\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home8\" role=\"tab\"><span><i class=\"ti-home\"></i></span></a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile8\" role=\"tab\"><span><i class=\"ti-user\"></i></span></a> </li>\n");
      out.write("												<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages8\" role=\"tab\"><span><i class=\"ti-email\"></i></span></a> </li>\n");
      out.write("											</ul>\n");
      out.write("											<!-- Tab panes -->\n");
      out.write("											<div class=\"tab-content tabcontent-border\">\n");
      out.write("												<div class=\"tab-pane active\" id=\"home8\" role=\"tabpanel\">\n");
      out.write("													<div class=\"p-20\">\n");
      out.write("														<h5>Best Clean Tab ever</h5>\n");
      out.write("														<h6>you can use it with the small code</h6>\n");
      out.write("														<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a.</p>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div class=\"tab-pane  p-20\" id=\"profile8\" role=\"tabpanel\">2</div>\n");
      out.write("												<div class=\"tab-pane p-20\" id=\"messages8\" role=\"tabpanel\">3</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6\">\n");
      out.write("									<div class=\"card\">\n");
      out.write("										<div class=\"card-body\">\n");
      out.write("											<h4 class=\"card-title\">Customtab vertical Tab</h4>\n");
      out.write("											<!-- Nav tabs -->\n");
      out.write("											<div class=\"vtabs \">\n");
      out.write("												<ul class=\"nav nav-tabs tabs-vertical\" role=\"tablist\">\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home9\" role=\"tab\"><span><i class=\"ti-home\"></i></span></a> </li>\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile9\" role=\"tab\"><span><i class=\"ti-user\"></i></span></a> </li>\n");
      out.write("													<li class=\"nav-item\"> <a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages9\" role=\"tab\"><span><i class=\"ti-email\"></i></span></a> </li>\n");
      out.write("												</ul>\n");
      out.write("												<!-- Tab panes -->\n");
      out.write("												<div class=\"tab-content\">\n");
      out.write("													<div class=\"tab-pane active\" id=\"home9\" role=\"tabpanel\">\n");
      out.write("														<div class=\"p-20\">\n");
      out.write("															<h5>Best Clean Tab ever</h5>\n");
      out.write("															<h6>you can use it with the small code</h6>\n");
      out.write("															<p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a.</p>\n");
      out.write("														</div>\n");
      out.write("													</div>\n");
      out.write("													<div class=\"tab-pane  p-20\" id=\"profile9\" role=\"tabpanel\">2</div>\n");
      out.write("													<div class=\"tab-pane p-20\" id=\"messages9\" role=\"tabpanel\">3</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>	\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-12\">\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <p>2018 Â© Admin Board. - <a href=\"#\">example.com</a></p>\n");
=======
      out.write("<style>\n");
      out.write("/* 자동배너 부분 */\n");
      out.write("html, body { box-sizing: border-box; padding: 0; margin: 0; text-align: center; }\n");
      out.write("    *, *:before, *:after { box-sizing: inherit; }\n");
      out.write("    .clearfix:after { content: ''; display: block; clear: both; float: none; }\n");
      out.write("    .title { margin-bottom: 0; text-align: center; font-size: 30px; color: #333; }\n");
      out.write("    .link, .link:visited { display: inline-block; margin: 20px 0; color: #555; text-decoration: none; font-weight: bold; }\n");
      out.write("    .link:hover, .link:focus { color: #9fd6c2; }\n");
      out.write("    /* container - body */\n");
      out.write("    #container { width: 1000px; margin: auto; }\n");
      out.write("    .slide_wrap { position: relative; width: 400px; margin: auto; padding-bottom: 30px; }\n");
      out.write("    .slide_box { width: 100%; margin: auto; overflow-x: hidden; }\n");
      out.write("    /*밑에가 슬라이드 이미지 칸에 대한 부분*/\n");
      out.write("    .slide_content { display: table; float: left; width: 400px; height: 400px; }\n");
      out.write("    /*밑에가 슬라이드 내의 글자*/\n");
      out.write("    .slide_content > p { display: table-cell; vertical-align: middle; text-align: center; font-size: 100px; font-weight: bold; color: #555; }\n");
      out.write("    .slide_content.slide01 { background: #ddbdff; }\n");
      out.write("    .slide_content.slide02 { background: #9fd6c2; }\n");
      out.write("    .slide_content.slide03 { background: #abe2f7; }\n");
      out.write("    .slide_content.slide04 { background: #f08c78; }\n");
      out.write("    /* .slide_content.slide05 { background: #fbdb65; } */\n");
      out.write("    .slide_btn_box > button { position: absolute; top: 50%; margin-top: -45px; width: 60px; height: 60px; font-size: 16px; color: white; background: navy; border: 1px solid #ddd; cursor: pointer; }\n");
      out.write("    .slide_btn_box > .slide_btn_prev { left: -100px; }\n");
      out.write("    .slide_btn_box > .slide_btn_next { right: -100px; }\n");
      out.write("    .slide_pagination { position: absolute; left: 50%; bottom: 0; list-style: none; margin: 0; padding: 0; transform: translateX(-50%); }\n");
      out.write("    .slide_pagination .dot { display: inline-block; width: 15px; height: 15px; margin: 0 5px; overflow: hidden; background: #ddd; border-radius: 50%; transition: 0.3s; }\n");
      out.write("    .slide_pagination .dot.dot_active { background: #333; }\n");
      out.write("    .slide_pagination .dot a { display: block; width: 100%; height: 100%; }\n");
      out.write(" \n");
      out.write(" /* 두번째 버튼 부분 */ \n");
      out.write(" .btn {\n");
      out.write("  text-decoration: none;\n");
      out.write("  font-size:15pt;  \n");
      out.write("  background-color: navy;\n");
      out.write("  color: white;\n");
      out.write("  padding:10px 20px 10px 20px;\n");
      out.write("  margin:10px;\n");
      out.write("  display:inline-block;\n");
      out.write("  border-radius: 10px;\n");
      out.write("  transition:all 0.2s;\n");
      out.write("  text-shadow:0px -2px black;\n");
      out.write(" }\n");
      out.write(" .btn:active {\n");
      out.write("  transform:translateY(5px);\n");
      out.write(" }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<h5>뉴스 /  백신 정보</h5>\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("<!-- 1. 코로나/백신 정보 (자동 슬라이드) -->\n");
      out.write("<h6>자동 배너, 코로나 확진자 수/백신접종현황/예방접종 사전예약 날짜/QnA</h6>\n");
      out.write("\n");
      out.write("<!-- 자동배너 (이미지 넣고, 수정해야함) -->\n");
      out.write("  <div id=\"container\">\n");
      out.write("    <div class=\"slide_wrap\">\n");
      out.write("      <div class=\"slide_box\">\n");
      out.write("        <div class=\"slide_list clearfix\">\n");
      out.write("          <div class=\"slide_content slide01\">\n");
      out.write("            <p>1</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"slide_content slide02\">\n");
      out.write("            <p>2</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"slide_content slide03\">\n");
      out.write("            <p>3</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"slide_content slide04\">\n");
      out.write("            <p>4</p>\n");
      out.write("          </div>\n");
      out.write("         <!--<div class=\"slide_content slide05\">\n");
      out.write("            <p>5</p>\n");
      out.write("          </div>  --> \n");
      out.write("        </div>\n");
      out.write("        <!-- // .slide_list -->\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_box -->\n");
      out.write("      <div class=\"slide_btn_box\">\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\">이전</button>\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\">다음</button>\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_btn_box -->\n");
      out.write("      <ul class=\"slide_pagination\"></ul>\n");
      out.write("      <!-- // .slide_pagination -->\n");
      out.write("    </div>\n");
      out.write("    <!-- // .slide_wrap -->\n");
      out.write("  </div>\n");
      out.write("  <!-- // .container -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("<!-- 2. 코로나/ 백신 정보로 넘어가는 버튼 -->\n");
      out.write("<h6>버튼을 클릭하면 해당 페이지로 이동함</h6>\n");
      out.write("<a class=\"btn\" href=\"coronainfo.jsp\">코로나 정보</a>\n");
      out.write("<a class=\"btn\" href=\"vaccineinfo.jsp\">백신 정보</a>\n");
      out.write("<a class=\"btn\" href=\"vaccination.jsp\">예방접종 정보</a>\n");
      out.write("<a class=\"btn\" href=\"qna.jsp\">QnA</a>\n");
      out.write("<hr>\n");
      out.write("<!-- 3. 실시간 뉴스 -->\n");
      out.write("<h6>크롤링으로 실시간 뉴스 가져오기</h6>\n");
      out.write("\n");
      out.write("<hr>\n");
      out.write("                <!-- /# row -->\n");
      out.write("                <section id=\"main-content\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-12\">\n");
      out.write("                            <div id=\"extra-area-chart\"></div>\n");
      out.write("                            <div id=\"morris-line-chart\"></div>\n");
      out.write("                            <div class=\"footer\">\n");
      out.write("                                <p>2018 © Admin Board. -\n");
      out.write("                                    <a href=\"#\">example.com</a>\n");
      out.write("                                </p>\n");
>>>>>>> Stashed changes
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
<<<<<<< Updated upstream
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
=======
      out.write("  \n");
>>>>>>> Stashed changes
      out.write("    <!-- jquery vendor -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\n");
      out.write("    <!-- nano scroller -->\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\n");
      out.write("    <!-- sidebar -->\n");
      out.write("    \n");
      out.write("    <!-- bootstrap -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script><script src=\"assets/js/scripts.js\"></script>\n");
      out.write("    <!-- scripit init-->\n");
      out.write("\n");
<<<<<<< Updated upstream
=======
      out.write("<!-- 자동배너 부분의 스크립트 -->\n");
      out.write("<script>\n");
      out.write("    (function () {\n");
      out.write("      const slideList = document.querySelector('.slide_list');  // Slide parent dom\n");
      out.write("      const slideContents = document.querySelectorAll('.slide_content');  // each slide dom\n");
      out.write("      const slideBtnNext = document.querySelector('.slide_btn_next'); // next button\n");
      out.write("      const slideBtnPrev = document.querySelector('.slide_btn_prev'); // prev button\n");
      out.write("      const pagination = document.querySelector('.slide_pagination');\n");
      out.write("      const slideLen = slideContents.length;  // slide length\n");
      out.write("      const slideWidth = 400; // slide width\n");
      out.write("      const slideSpeed = 300; // slide speed\n");
      out.write("      const startNum = 0; // initial slide index (0 ~ 4)\n");
      out.write("      \n");
      out.write("      slideList.style.width = slideWidth * (slideLen + 2) + \"px\";\n");
      out.write("      \n");
      out.write("      // Copy first and last slide\n");
      out.write("      let firstChild = slideList.firstElementChild;\n");
      out.write("      let lastChild = slideList.lastElementChild;\n");
      out.write("      let clonedFirst = firstChild.cloneNode(true);\n");
      out.write("      let clonedLast = lastChild.cloneNode(true);\n");
      out.write("\n");
      out.write("      // Add copied Slides\n");
      out.write("      slideList.appendChild(clonedFirst);\n");
      out.write("      slideList.insertBefore(clonedLast, slideList.firstElementChild);\n");
      out.write("\n");
      out.write("      // Add pagination dynamically\n");
      out.write("      let pageChild = '';\n");
      out.write("      for (var i = 0; i < slideLen; i++) {\n");
      out.write("        pageChild += '<li class=\"dot';\n");
      out.write("        pageChild += (i === startNum) ? ' dot_active' : '';\n");
      out.write("        pageChild += '\" data-index=\"' + i + '\"><a href=\"#\"></a></li>';\n");
      out.write("      }\n");
      out.write("      pagination.innerHTML = pageChild;\n");
      out.write("      const pageDots = document.querySelectorAll('.dot'); // each dot from pagination\n");
      out.write("\n");
      out.write("      slideList.style.transform = \"translate3d(-\" + (slideWidth * (startNum + 1)) + \"px, 0px, 0px)\";\n");
      out.write("\n");
      out.write("      let curIndex = startNum; // current slide index (except copied slide)\n");
      out.write("      let curSlide = slideContents[curIndex]; // current slide dom\n");
      out.write("      curSlide.classList.add('slide_active');\n");
      out.write("\n");
      out.write("      /** Next Button Event */\n");
      out.write("      slideBtnNext.addEventListener('click', function() {\n");
      out.write("        if (curIndex <= slideLen - 1) {\n");
      out.write("          slideList.style.transition = slideSpeed + \"ms\";\n");
      out.write("          slideList.style.transform = \"translate3d(-\" + (slideWidth * (curIndex + 2)) + \"px, 0px, 0px)\";\n");
      out.write("        }\n");
      out.write("        if (curIndex === slideLen - 1) {\n");
      out.write("          setTimeout(function() {\n");
      out.write("            slideList.style.transition = \"0ms\";\n");
      out.write("            slideList.style.transform = \"translate3d(-\" + slideWidth + \"px, 0px, 0px)\";\n");
      out.write("          }, slideSpeed);\n");
      out.write("          curIndex = -1;\n");
      out.write("        }\n");
      out.write("        curSlide.classList.remove('slide_active');\n");
      out.write("        pageDots[(curIndex === -1) ? slideLen - 1 : curIndex].classList.remove('dot_active');\n");
      out.write("        curSlide = slideContents[++curIndex];\n");
      out.write("        curSlide.classList.add('slide_active');\n");
      out.write("        pageDots[curIndex].classList.add('dot_active');\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      /** Prev Button Event */\n");
      out.write("      slideBtnPrev.addEventListener('click', function() {\n");
      out.write("        if (curIndex >= 0) {\n");
      out.write("          slideList.style.transition = slideSpeed + \"ms\";\n");
      out.write("          slideList.style.transform = \"translate3d(-\" + (slideWidth * curIndex) + \"px, 0px, 0px)\";\n");
      out.write("        }\n");
      out.write("        if (curIndex === 0) {\n");
      out.write("          setTimeout(function() {\n");
      out.write("            slideList.style.transition = \"0ms\";\n");
      out.write("            slideList.style.transform = \"translate3d(-\" + (slideWidth * slideLen) + \"px, 0px, 0px)\";\n");
      out.write("          }, slideSpeed);\n");
      out.write("          curIndex = slideLen;\n");
      out.write("        }\n");
      out.write("        curSlide.classList.remove('slide_active');\n");
      out.write("        pageDots[(curIndex === slideLen) ? 0 : curIndex].classList.remove('dot_active');\n");
      out.write("        curSlide = slideContents[--curIndex];\n");
      out.write("        curSlide.classList.add('slide_active');\n");
      out.write("        pageDots[curIndex].classList.add('dot_active');\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      /** Pagination Button Event */\n");
      out.write("      let curDot;\n");
      out.write("      Array.prototype.forEach.call(pageDots, function (dot, i) {\n");
      out.write("        dot.addEventListener('click', function (e) {\n");
      out.write("          e.preventDefault();\n");
      out.write("          curDot = document.querySelector('.dot_active');\n");
      out.write("          curDot.classList.remove('dot_active');\n");
      out.write("          \n");
      out.write("          curDot = this;\n");
      out.write("          this.classList.add('dot_active');\n");
      out.write("\n");
      out.write("          curSlide.classList.remove('slide_active');\n");
      out.write("          curIndex = Number(this.getAttribute('data-index'));\n");
      out.write("          curSlide = slideContents[curIndex];\n");
      out.write("          curSlide.classList.add('slide_active');\n");
      out.write("          slideList.style.transition = slideSpeed + \"ms\";\n");
      out.write("          slideList.style.transform = \"translate3d(-\" + (slideWidth * (curIndex + 1)) + \"px, 0px, 0px)\";\n");
      out.write("        });\n");
      out.write("      });\n");
      out.write("    })();\n");
      out.write("  </script>\n");
>>>>>>> Stashed changes
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
